config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'play/:id' => 'game#play'
  # get 'signup'  => 'messages#new'
  # get 'messages/new'
  # get 'static_pages/home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  root 'static_pages#home'
  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :messages
  resources :picks
  resources :users
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
    has_many :picks, foreign_key: 'transmit_id', class_name: "Pick"
    has_many :picks, foreign_key: 'message_id', class_name: "Pick"
    has_one :game,foreign_key: 'first_page_id', class_name: "Game"

    validates :value, presence: true, length: { minimum: 2 },
                      uniqueness: false
    validates :comment,
              uniqueness: false, presence: false
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # before_action :admin_user,     only: [:destroy, :create, :edit, :index, :new, :show, :update]
  before_action :second_user,     only: [:destroy, :create, :edit, :index, :new, :show, :update]
  # before_action :check_user,     only: [:destroy, :create]

  def show
      @message = Message.find(params[:id])
      @picks = @message.picks.all
  end

  def destroy
    Message.find(params[:id]).destroy
    # flash[:success] = "User deleted"
    redirect_to messages_url
  end

  def new
      @message = Message.new
  end

  def create
    @message = Message.new(message_params)    # Не окончательная реализация!
    if @message.save
      redirect_to @message
    else
      render 'new'
    end
  end

  def index
      @messages = Message.all
  end

  def edit
      @message = Message.find(params[:id])
  end

  def update
    @message = Message.find(params[:id])
    if @message.update_attributes(message_params)
      redirect_to @message
    else
      render 'edit'
    end
  end

  private

    def message_params
      params.require(:message).permit(:value, :comment)
    end

  # Подтверждает администратора.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def first_user
    unless logged_in? && current_user.id == 1
      redirect_to root_path
    end
  end

  def second_user
    unless logged_in? && current_user.id == 2
      redirect_to root_path
    end
  end

end

app/helpers/messages_helper.rb
module MessagesHelper

  # Возвращает true, если у сообщения есть комментарий, иначе false.
  def comment?(message)
    message.comment != ""
  end

  # Возвращает название смайла комментария
  def comment_smile(message)
    # char = message.comment[-1]
    case message.comment[-1]
    when 'A'
      'angry_final4.png'
    when 'N'
      'normal_final4.png'
    when 'E'
      'evil_smile1.png'
    else
      'smile_final4.png'
    end
  end

  # Возвращает текст комментария
  def comment_text(message)
    message.comment[0..-2]
  end

  # Возвращает текст сообщения
  def message_text(message)
    image?(message) ? message.value[0..message.value.index('$')-1] : message.value
  end

  # Возвращает картинку
  def message_image(message)
    image?(message) ? message.value[message.value.index('$')+1..-1] +'.jpg' : 'default.jpg'
  end

  # Возвращает true, если сообщение содержит картинку
  def image?(message)
    message.value.include?('$')
  end

end

app/views/messages/_message.html.erb
<li style="font-size: 15px">
  <span  style="color: white">ID: <%= link_to message.id, message %></span><br />
  <span style="color: white">TEXT: "<%= message.value %>"</span><br />
  <span style="color: white">COMMENT: "<%= message.comment %>"</span>

  <%= link_to "edit", edit_message_url(message), method: :get %>
  <%= link_to "delete", message, method: :delete,
              data: { confirm: "You sure?" } %>

  <% for p in message.picks.all %>
    <br />
      <span  style="color: white; margin-left: 100px;">ID: <%= link_to p.id, p %></span><br />
      <span  style="color: white; margin-left: 100px;" class="context">CONTEXT: "<%= p.context %>"</span>
      <%= link_to "edit", edit_pick_url(p), method: :get %>
    <%= link_to "delete", p, method: :delete,
                data: { confirm: "You sure?" } %>

  <% end %>

</li>

app/views/messages/edit.html.erb
<% provide(:title, "Edit message") %>
<h1 style="color: white">Update your message</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= form_for(@message) do |f| %>

      <%= f.label :value %>
      <%= f.text_field :value, class: 'form-control' %>

      <%= f.label :comment, "Comment" %>
      <%= f.text_field :comment %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/messages/index.html.erb
<% provide(:title, 'All messages') %>
<h1 style="color: white" >All messages</h1>

<ul class="users">
  <%= render @messages %>
</ul>

app/views/messages/new.html.erb
<% provide(:title, 'New Message') %>
<h1 style="color: white">Messages#new</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@message) do |f| %>
      <%= f.label :value, "Text" %>
      <%= f.text_field :value %>

      <%= f.label :comment, "Comment" %>
      <%= f.text_field :comment %>

      <%= f.submit "Create new message", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/messages/show.html.erb
<h3 style="color: white" >Message</h3>
<%= render @message %>
<!--<h4>Choices: <%#= render @picks %></h4>-->