config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'play/:id' => 'game#play'
  # get 'signup'  => 'messages#new'
  # get 'messages/new'
  # get 'static_pages/home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  root 'static_pages#home'
  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :messages
  resources :picks
  resources :users
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse my_header">
  <div class="container" onclick="show('navb', 'inline')">

    <nav>
      <%= link_to "WN", root_path, id: "logo" %>
      <ul id="navb" class="nav navbar-nav navbar-right">
        <li><%= link_to "Главная",    root_path %></li>
        <li><%= link_to "Помощь",    help_path %></li>
        <li><%= link_to "О Сайте",   about_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
          <li>
            <%= link_to "Выход", logout_path, method: :delete %>
          </li>
        <% else %>
          <li><%= link_to "Вход", login_path %></li>
          <li><%= link_to "Регистрация", signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_warner.html.erb
<div class="warner_block">

  Предупреждение!
  <br>
  Не знаю зачем вы зашли на эту страницу, но она не используется на сайте в данный момент.
  <br>
  Я не стал убирать доступ к профилю, поэтому можете конечно поковырять, если очень хотите.

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Web-Novels</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('logo.ico') %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

    <%= yield %>
    <%#= debug(params) if Rails.env.development? %>
  </body>
</html>